name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 12 * * *' # Se ejecuta todos los días a las 12:00 UTC
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://appemergenciapy-evagabxskaw7cqvwex2d3k.streamlit.app/
